# Generated by Django 4.2.2 on 2023-06-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='actiontype',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='C', max_length=2),
        ),
    ]
