# Generated by Django 4.2.2 on 2023-06-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
    ]
