# Generated by Django 4.2.2 on 2023-06-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0002_alter_card_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='blocked',
            new_name='is_blocked',
        ),
        migrations.AlterField(
            model_name='card',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
